// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: [
            'eslint.config.mjs',
            'packages/contracts/scripts/generate.ts',
            'apps/web/postcss.config.mjs',
          ],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
    },
  },
  {
    ignores: [
      '**/dist/**',
      // Next's generated route types, same class as `dist` — build output, not
      // source, and not covered by any tsconfig's `include`.
      '**/.next/**',
      '**/playwright-report/**',
      // Generated by `next build` and explicitly marked "should not be edited".
      'apps/web/next-env.d.ts',
      '**/test-results/**',
      '**/node_modules/**',
      '**/*.js',
      'prisma/generated/**',
      'python/**',
      'packages/contracts/src/generated/**',
    ],
  },
);
